### PR TITLE
Adapted to latest NFC implementation

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@kenchris, @riju, PTAL.

**Review by kenchris — APPROVED** [review]

**Comment by kenchris** [comment]
You need to build and move the new build into /docs for it to update the live site

**Comment by Honry** [comment]
OK, I will build it right now.

**Comment by kenchris** [comment]
@Honry feel free to add instructions to the README.md or similar so that people will know how to deploy the site :-)

**Comment by Honry** [comment]
@kenchris, sure.

**Comment by Honry** [comment]
hey, @kenchris, what's the version of Polymer this demo is using? I encountered a build error with polymer-cli 1.9.11, even failed on 1.8.0.
```
info: [cli.command.build]    Clearing build/ directory...
warn: [cli.build.optimize-streams]    js-transform: Unable to optimize /home/honry/work/upstream/honry/demo/webnfc-groceries/src/dismissable-item.js
{ err:
   'This experimental syntax requires enabling one of the following parser plugin(s): \'decorators-legacy, decorators\' (33:0)' }
info: [cli.build.build]    (default) Building...
warn: [cli.build.optimize-streams]    js-transform: Unable to optimize /home/honry/work/upstream/honry/demo/webnfc-groceries/src/groceries-list.js
{ err:
   'This experimental syntax requires enabling one of the following parser plugin(s): \'decorators-legacy, decorators\' (12:0)' }
warn: [cli.build.optimize-streams]    js-transform: Unable to optimize /home/honry/work/upstream/honry/demo/webnfc-groceries/src/grocery-store.js
{ err:
   'Cannot find module \'@babel/plugin-proposal-class-properties\' from \'/home/honry/work/upstream/honry/demo/webnfc-groceries\'' }
warn: [cli.build.optimize-streams]    js-transform: Unable to optimize /home/honry/work/upstream/honry/demo/webnfc-groceries/src/main-app.js
{ err:
   'This experimental syntax requires enabling one of the following parser plugin(s): \'decorators-legacy, decorators\' (20:0)' }
warn: [cli.build.optimize-streams]    js-transform: Unable to optimize /home/honry/work/upstream/honry/demo/webnfc-groceries/src/mwc-list-item-css.js
{ err:
   'Cannot find module \'@babel/plugin-proposal-class-properties\' from \'/home/honry/work/upstream/honry/demo/webnfc-groceries\'' }


  <script type="module" src="./src/main-app.js"></script>
                            ~~~~~~~~~~~~~~~~~~~

file:///home/honry/work/upstream/honry/demo/webnfc-groceries/index.html(33,29) error [could-not-load] - Unable to load import: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (20:0)
error: [cli.main]   Promise rejection: Error: 1 error(s) occurred during build.
error: [cli.main]   Error: 1 error(s) occurred during build.
    at BuildAnalyzer._done (/home/honry/.nvm/versions/node/v10.10.0/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:275:36)
    at BuildAnalyzer.<anonymous> (/home/honry/.nvm/versions/node/v10.10.0/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:236:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/honry/.nvm/versions/node/v10.10.0/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:17:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by kenchris** [comment]
It is not using polymer cli but just rollup.

**Comment by kenchris** [comment]
just do npm install and then npm run build

**Comment by Honry** [comment]
Yeah! It woks. Thanks!

**Pull request merged**
